version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Ronaldo81.
      MYSQL_DATABASE: password_manage

    volumes:
      - ./dump:/var/lib/mysql:rw

    networks:
      - my-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5051:5050"
    environment:
      DATABASE_URL: mysql://admin:Ronaldo81.@db:3306/password_manage" 
      TOKEN_SECRET: 673d0b35fcd2c89fdd49a18fe4a54325c872605b4bd00bb4314ff266d4c17a1f0c4659b7eb1758a2cb3637b2f568ca3ee808d72c3f924beb88797dc398568403
      user: root
      password: Ronaldo81.
      
    depends_on:
      - db

    networks:
      - my-network

  nginx:
    image: nginx:latest
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - '80:80'

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf


    depends_on:
      - react

  react:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - REACT_APP_SERVER_ENDPOINT=http://server:5050
    ports:
      - "3005:80"
    depends_on:
      - server

    networks:
      - my-network

networks:
  my-network:
    driver: bridge